pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - "status-success=ci/circleci: shellcheck"
      - "status-success=ci/circleci: lint"
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: install-cni"
      - "status-success=ci/circleci: e2e-dind"
      - "status-success=ci/circleci: e2e-dind-istio1.1"
      - "status-success=ci/circleci: e2e-dind-istio1.2"
      - status-success=cla/google
      - "#approved-reviews-by>=1"
      - label!=do-not-merge
      - label!=do-not-merge/work-in-progress
      - label!=do-not-merge/hold
    actions:
      merge:
        method: squash
        strict: false
