hub: gcr.io/istio-testing
tag: latest
pullPolicy: Always

logLevel: info

# Configuration file to insert istio-cni plugin configuration
# by default this will be the first file found in the cni-conf-dir
# Example
# cniConfFileName: 10-calico.conflist

# CNI bin and conf dir override settings
# defaults:
cniBinDir: /opt/cni/bin
cniConfDir: /etc/cni/net.d
cniConfFileName: ""

excludeNamespaces:
  - istio-system

# Custom annotations on pod level, if you need them
podAnnotations: {}

# If this value is set a RoleBinding will be created
# in the same namespace as the istio-cni DaemonSet is created.
# This can be used to bind a preexisting ClusterRole to the istio/cni ServiceAccount
# e.g. if you use PodSecurityPolicies
psp_cluster_role: ""

repair:
  enabled: true
  hub: gcr.io/istio-testing
  tag: latest

  initContainerName: "istio-validation"

  labelPods: "true"
  createEvents: "true"
  deletePods: "false"

  brokenPodLabelKey: "cni.istio.io/uninitialized"
  brokenPodLabelValue: "true"