hub: gcr.io/istio-release
tag: release-1.2-latest-daily
pullPolicy: Always

logLevel: info

# Configuration file to insert istio-cni plugin configuration
# by default this will be the first file found in the cni-conf-dir
# Example
# cniConfFileName: 10-calico.conflist

# CNI bin and conf dir override settings
# defaults:
cniBinDir: /home/kubernetes/bin
cniConfDir: /etc/cni/net.d

excludeNamespaces:
  - istio-system
