FROM amd64/alpine:3.8

LABEL maintainer "Tim Swanson <tiswanso@cisco.com"

# add bash to allow install-cni.sh to trap process signals
RUN apk --update add jq bash && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

ADD istio-cni /opt/cni/bin/
ADD istio-iptables.sh /opt/cni/bin/
ADD install-cni.sh /install-cni.sh
ADD istio-cni.conf.default /istio-cni.conf.tmp

ENV PATH=$PATH:/opt/cni/bin
VOLUME /opt/cni
WORKDIR /opt/cni/bin
CMD ["/install-cni.sh"]
