FROM ubuntu:xenial

LABEL description="Istio CNI daemonset."

RUN apt-get update && apt-get install -qqy --no-install-recommends \
jq='1.5*' \
&& rm -rf /var/lib/apt/lists/*

COPY istio-cni-daemonset /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
VOLUME /opt/cni
WORKDIR /opt/cni/bin
CMD ["istio-cni-daemonset"]
